export default [
  {
    side2: 'Отбивная куриная',
    side1: 'Пюре картофельное',
    salad: 'Салат ветчина,капуста,кукуруза,майонез',
    option_number: 1,
    main: 'Суп сырный с грибами',
    id: 1,
    date: '2017-08-16',
    cost_without_main: 70,
    cost: 75,
  },
  {
    side2: 'Хек жареный',
    side1: 'Рис с овощами',
    salad: 'Овощной с пармезаном',
    option_number: 2,
    main: 'Суп рыбный',
    id: 2,
    date: '2017-08-16',
    cost_without_main: 65,
    cost: 70,
  },
  {
    side2: 'Тефтеля мясная в томате',
    side1: 'Пюре картофельное',
    salad: 'Курица,морковь по корейски,яйцо,сыр,майонез',
    option_number: 3,
    main: 'Суп с кнелями и лапшой',
    id: 3,
    date: '2017-08-16',
    cost_without_main: 60,
    cost: 70,
  },
  {
    side2: 'Мясо с ананасом',
    side1: 'Картофель жареный по домашнему',
    salad: 'Овощной салат',
    option_number: 4,
    main: 'Окрошка',
    id: 4,
    date: '2017-08-16',
    cost_without_main: 70,
    cost: 75,
  },
];
